# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [13]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [16]:
A = np.arange(1, 16).reshape(3,5)

In [18]:
import numpy as np

A = np.arange(1, 16).reshape(3, 5)

print("Dimension (antal axlar):", A.ndim)
print("Shape:", A.shape)
print("Size (antal element):", A.size)
print("Datatype:", A.dtype)

Dimension (antal axlar): 2
Shape: (3, 5)
Size (antal element): 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [20]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [22]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

print("Elementvis subtraktion (B - C):\n", B - C)
print("\nElementvis multiplikation (B * C):\n", B * C)
print("\nMatrismultiplikation (B @ C):\n", B @ C)

Elementvis subtraktion (B - C):
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementvis multiplikation (B * C):
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrismultiplikation (B @ C):
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [26]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
B = np.arange(1, 10).reshape(3, 3)

print("Exponentierad matris:\n", np.exp(B))
print("\nMinsta värde i hela matrisen:", np.min(B))
print("Minsta värde per rad:", np.min(B, axis=1))
print("Minsta värde per kolumn:", np.min(B, axis=0))
print("\nIndex för minsta värde i hela matrisen:", np.argmin(B))
print("Index för minsta värde per rad:", np.argmin(B, axis=1))
print("\nSumma av alla element:", np.sum(B))
print("Medelvärde per kolumn:", np.mean(B, axis=0))
print("Median per kolumn:", np.median(B, axis=0))

Exponentierad matris:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minsta värde i hela matrisen: 1
Minsta värde per rad: [1 4 7]
Minsta värde per kolumn: [1 2 3]

Index för minsta värde i hela matrisen: 0
Index för minsta värde per rad: [0 0 0]

Summa av alla element: 45
Medelvärde per kolumn: [4. 5. 6.]
Median per kolumn: [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [30]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [32]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [34]:
print(A)
print("\nSlicing med A[1]:", A[1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

Slicing med A[1]: [ 6  7  8  9 10]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [36]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [38]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [40]:
print("Elementvis iteration:")
for element in A.flat:
    print(element)

Elementvis iteration:
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [42]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [44]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [47]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [50]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [52]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [58]:
def add_mult_matrices(A, B, operation):
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise ValueError("Båda argumenten måste vara numpy.ndarray")
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation måste vara 'add' eller 'multiply'")
    
    if operation == 'add':
        if A.shape != B.shape:
            raise ValueError("Matriserna måste ha samma storlek för addition")
        return A + B
    else:  # multiply
        if A.shape[1] != B.shape[0]:
            raise ValueError("Antal kolumner i A måste matcha antal rader i B")
        return A @ B

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [62]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print("Addition:", v1 + v2)
print("Skalärprodukt:", np.dot(v1, v2))

Addition: [5 7 9]
Skalärprodukt: 32


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [64]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrisaddition:", A + B)
print("Matrismultiplikation:", A @ B)
print("Determinant:", np.linalg.det(A))
print("Invers:", np.linalg.inv(A))

Matrisaddition: [[ 6  8]
 [10 12]]
Matrismultiplikation: [[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Invers: [[-2.   1. ]
 [ 1.5 -0.5]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [66]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [68]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [70]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [72]:
v1 = np.arange(4)
v2 = v1[-2:]
print("v1:", v1)
print("v2:", v2)
print("\nv1.base:", v1.base)
print("v2.base:", v2.base)

v2[-1] = 123
print("\nEfter ändring i v2:")
print("v1:", v1)
print("v2:", v2)

v1: [0 1 2 3]
v2: [2 3]

v1.base: None
v2.base: [0 1 2 3]

Efter ändring i v2:
v1: [  0   1   2 123]
v2: [  2 123]
